all:	configure

configure:	 Makefile.in configure.ac
	@autoheader
	@autoconf
	@rm -rf *.cache

clean:
	@if [ -f Makefile ]; then make clean; fi
	@rm -rvf Makefile configure config.* src/.ui src/.obj src/.moc
	@rm -rvf src/Makefile src/config.* src/*.pri src/*.desktop src/*.mak
	@rm -rvf skulpture/Makefile skulpture/.ui skulpture/.obj skulpture/.moc
	@rm -rvf skulpture/*.pri skulpture/*.mak
	@rm -rvf *.cache *.log *.status *.spec *.mak
