all:	configure

configure:	 Makefile.in configure.ac
	@autoheader
	@autoconf
	@rm -rf *.cache

clean:
	@if [ -f Makefile ]; then make clean; fi || true
	@rm -rvf Makefile configure config.*
	@rm -rvf src/.ui src/.obj src/.moc
	@rm -rvf src/config.* src/*.pri src/*.mak src/*.desktop
	@rm -rvf skulpture/.ui skulpture/.obj skulpture/.moc
	@rm -rvf skulpture/*.pri skulpture/*.mak
	@rm -rvf *.cache *.log *.status *.spec
