
#define PACKAGE_NAME    "QXGEdit"
#define PACKAGE_VERSION "0.0.1.10"

#define PACKAGE_STRING  PACKAGE_NAME " " PACKAGE_VERSION

#define CONFIG_PREFIX   "."
#define CONFIG_DEBUG    1

#undef  CONFIG_STACKTRACE
