.TH qxgedit "1" "April 16, 2026"
.SH NAME
qxgedit \- Qt XG Editor
.SH SYNOPSIS
.B qxgedit
[\fIoptions\fR] [\fIsyx-file\fR]
.SH DESCRIPTION
This manual page documents briefly the
.B qxgedit
command-line options.
.PP
\fBQXGEdit\fP is a Qt GUI for editing MIDI System Exclusive files
for XG devices (eg. Yamaha DB50XG).
.SH OPTIONS
.HP
\fB\-?\fR, \fB\-\-help\fR
.IP
Displays help on command-line options.
.HP
\fB\-v\fR, \fB\-\-version\fR
.IP
Show version information.
.SH FILES
Configuration settings are stored in ~/.config/rncbc.org/QXGEdit.conf
.SH AUTHOR
QXGEdit was written by Rui Nuno Capela.
